#!/bin/bash

set -ex


# usage docker-shell <arch> <distro> [cmd]

# shared volume
shared_repo=/Repos
shared_data=/Data
shared_home=${HOME}
shared_misc=/misc
shared_opt=/opt
shared_display=:0

  arch=${1}
distro=${2}
   cmd=${3}

if [ $# == 0 ]; then
	#default arch and distro
	arch=amd64
	distro=bionic
fi


docker run --rm \
	-it \
	--privileged \
	-e DISPLAY=${shared_display} \
	-u $(id -u):$(id -g) \
	-h ${distro} \
	-v /tmp/.X11-unix:/tmp/.X11-unix:rw \
	-v /etc/passwd:/etc/passwd:ro \
	-v /etc/group:/etc/group:ro \
	-v /etc/shadow:/etc/shadow:ro \
	-v /etc/sudoers.d:/etc/sudoers.d:ro \
	-v ${shared_repo}:${shared_repo} \
	-v ${shared_data}:${shared_data} \
	-v ${shared_home}:${shared_home} \
	-v ${shared_misc}:${shared_misc} \
	-v ${shared_opt}:${shared_opt} \
	-w ${PWD} \
	${distro}:${arch} ${cmd}
